project:
  type: website
  output-dir: docs

website:
  title: "Christopher Ormerod"
  navbar:
    left:
      - index.qmd
      - research.qmd
      - publications.qmd
      - experience.qmd

format:
  html:
    grid: 
      sidebar-width: 100px
      body-width: 1100px
    page-layout: full
    theme: morph
    css: styles.css
    toc: true
    backgroundcolor: white
    linestretch: 1.7
    fontcolor: black
