project:
  type: website
  output-dir: docs

website:
  title: "Christopher Ormerod"
  navbar:
    left:
      - index.qmd
      - about.qmd
      - publications.qmd

format:
  html:
    theme: morph
    css: styles.css
    toc: true
    backgroundcolor: white
    linestretch: 1.7
    fontcolor: black
